//! Generates the string catalogue from the existing C# .resx files.
//!
//! The .resx stay the single source of truth while the port is in flight, so translations can
//! never drift between the C# and Rust builds. Output is one sorted `&[(&str, &str)]` per
//! language, looked up by binary search: no runtime file IO, no dependency, and it costs
//! nothing at startup — which is the whole point of moving to Rust.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let resources = Path::new("../src/KRATE.Core/Resources");
    println!("cargo:rerun-if-changed={}", resources.display());

    let mut languages: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    let mut files: Vec<PathBuf> = fs::read_dir(resources)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", resources.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "resx"))
        .collect();
    files.sort();

    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        // "Strings" is the neutral (English) catalogue; "Strings.fr" is French.
        let lang = stem.strip_prefix("Strings.").unwrap_or("en").to_string();
        let text = fs::read_to_string(path).expect("resx must be valid UTF-8");
        languages.insert(lang, parse_resx(&text));
    }

    assert!(!languages.is_empty(), "no .resx files found in {}", resources.display());

    let mut out = String::from("// @generated by build.rs from ../src/KRATE.Core/Resources — do not edit.\n\n");
    let mut arms = String::new();

    for (lang, entries) in &languages {
        let ident = format!("L_{}", lang.replace('-', "_").to_uppercase());
        out.push_str(&format!(
            "static {ident}: [(&str, &str); {}] = [\n",
            entries.len()
        ));
        for (key, value) in entries {
            out.push_str(&format!("    ({:?}, {:?}),\n", key, value));
        }
        out.push_str("];\n\n");
        arms.push_str(&format!("        {lang:?} => &{ident},\n"));
    }

    out.push_str(&format!(
        "/// Every language shipped, most specific first. `en` is the fallback.\n\
         pub const LANGUAGES: [&str; {}] = [{}];\n\n\
         fn table(language: &str) -> &'static [(&'static str, &'static str)] {{\n\
         \x20   match language {{\n{arms}        _ => &L_EN,\n    }}\n}}\n",
        languages.len(),
        languages
            .keys()
            .map(|l| format!("{l:?}"))
            .collect::<Vec<_>>()
            .join(", "),
    ));

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("strings.rs");
    fs::write(&dest, out).expect("failed to write generated strings");
}

/// Minimal .resx reader: pulls `<data name="..."><value>...</value></data>` pairs.
/// A real XML parser would be a dependency for one shape of one file we control.
fn parse_resx(text: &str) -> BTreeMap<String, String> {
    let mut entries = BTreeMap::new();
    let mut rest = text;

    while let Some(start) = rest.find("<data ") {
        rest = &rest[start..];
        let Some(end) = rest.find("</data>") else { break };
        let block = &rest[..end];
        rest = &rest[end + "</data>".len()..];

        let Some(name) = between(block, "name=\"", "\"") else { continue };
        let Some(value) = between(block, "<value>", "</value>") else { continue };
        entries.insert(name.to_string(), unescape(value));
    }
    entries
}

fn between<'a>(text: &'a str, open: &str, close: &str) -> Option<&'a str> {
    let start = text.find(open)? + open.len();
    let end = text[start..].find(close)? + start;
    Some(&text[start..end])
}

/// The five XML entities that can appear in a resx value. `&amp;` is done last so an escaped
/// ampersand in the source ("&amp;lt;") does not get decoded twice into a bare "<".
fn unescape(value: &str) -> String {
    value
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}
